name: Daily Commit

on:
  schedule:
    - cron: '0 0 * * *' # Run daily at midnight UTC
  push:
    branches:
      - main # Trigger on manual changes to the main branch

jobs:
  update-activity:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Update a File
        run: |
          echo "Last updated on $(date)" >> update.log
          git config --global user.name "your-username"
          git config --global user.email "your-email@example.com"
          git add update.log
          git commit -m "Automated update on $(date)" || echo "No changes to commit"

      - name: Push Changes
        run: |
          git push
